services:
  postgres:
    image: postgres:17
    container_name: postgres_db_termografia
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: termografia
      POSTGRES_DB: db_termografia
      POSTGRES_TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
