name: Deploy vm-linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar ssh-agent com chave privada
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Conectar e executar comandos no servidor
        run: ssh -T joao@192.168.4.40 "uptime && echo OK"


      - name: Fazer deploy na rede local
        run: |
          ssh joao@192.168.4.40 <<'EOF'
          echo "INICIANDO DEPLOY"
          cd /home/joao/termografia
          git pull
          pnpm install --frozen-lockfile --reporter=append-only
          pnpm build
          pm2 restart termo-web
          echo "DEPLOY CONCLUÍDO"
          EOF

