name: Local Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 192.168.4.40 >> ~/.ssh/known_hosts

      - name: Testar conexão SSH
        run: |
          ssh -v joao@192.168.4.40 echo "Conectado com sucesso"

      - name: Fazer deploy na rede local
        run: |
          ssh -o LogLevel=DEBUG joao@192.168.4.40 "bash -s" <<'EOF'
          set -e
          echo "INICIANDO DEPLOY"
          cd /home/joao/termografia
          git pull
          pnpm install
          pnpm build
          pm2 restart termo-web
          echo "DEPLOY CONCLUÍDO"
          EOF
