name: Local Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Verificar chave gerada
        run: |
         ssh-keygen -y -f ~/.ssh/id_ed25519

      - name: Testar porta SSH
        run: nc -zv 192.168.4.40 22



      - name: Testar conexão SSH
        run: ssh -o StrictHostKeyChecking=no -T joao@192.168.4.40 echo "SSH OK"


      - name: Fazer deploy na rede local
        run: |
          ssh -o LogLevel=DEBUG -tt joao@192.168.4.40 <<'EOF'
          set -e
          echo "INICIANDO DEPLOY"
          cd /home/joao/termografia
          git pull
          pnpm install
          pnpm build
          pm2 restart termo-web
          echo "DEPLOY CONCLUÍDO"
          EOF
