name: Local Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Testar conexão SSH
        run: |
          ssh -v joao@192.168.4.40 echo "Conectado com sucesso"
   

      - name: Fazer deploy na rede local
        run: |
         ssh joao@192.168.4.40 << 'EOF'
          set -e
          set -x
          source ~/.bashrc
          cd /home/joao/termografia
          git pull
          pnpm install
          pnpm build
          pm2 restart termo-web
         EOF

